# Generated by Django 4.1.4 on 2022-12-11 07:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220930_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[core.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
